### PR TITLE
feat: Add support for browser authentication

### PR DESCRIPTION
**Pull request by dlouseiro**
The purpose of this PR is to add support for SSO authentication via external browser (documented [here](https://docs.snowflake.com/en/developer-guide/node-js/nodejs-driver-authenticate#using-single-sign-on-sso-through-a-web-browser)).

As I detailed in this [issue](https://github.com/MeltanoLabs/target-snowflake/issues/203), while the most common authentication methods used for production users (Snowflake service account) are basic authentication (user/password) and RSA key-pair authentication, local executions can be done with personal users which, in some companies' Snowflake setup don't have a password, but can only authenticate via SSO (using an external browser).

### Implementation details:
- Add new configuration property `use_browser_authentication`, which defaults to `false` (added to `README.md`, `meltano.yml` and `target_snowflake/target.py`)
- Added `secure-local-storage` extra to the `snowflake-connector-python` (needed for SSO tokens to be cacheable - documented [here](https://docs.snowflake.com/en/user-guide/admin-security-fed-auth-use#using-connection-caching-to-minimize-the-number-of-prompts-for-authentication-optional))
- Update `poetry.lock`
- Add `settings_group_validation` for the three possible flows: user/password, user/private_key_path and user/use_browser_authentication

Closes https://github.com/MeltanoLabs/target-snowflake/issues/203

### CODE REVIEW

**Comment by dlouseiro** [comment]
FYI, this is my first PR in this repo (or in any other repo from `MeltanoLabs` so I may have something missing). Would of course appreciate some help from the reviewers to guide me in the right direction!

**Comment by edgarrmondragon** [comment]
@dlouseiro thanks for contributing! Would you mind rebasing your branch to the latest `main`?

**Comment by dlouseiro** [comment]
> @dlouseiro thanks for contributing! Would you mind rebasing your branch to the latest `main`?

Sure, will do!

**Comment by dlouseiro** [comment]
> > @dlouseiro thanks for contributing! Would you mind rebasing your branch to the latest `main`?
> 
> Sure, will do!

DOne @edgarrmondragon

**Review by edgarrmondragon — APPROVED** [review]
LGTM!

**Pull request merged**
